σ dept_name = 'Biology' (course)
π name (instructor)
π name, salary (instructor)
π title σ (dept_name = 'Comp. Sci.') (course)
π year, semester σ dept_name = 'Comp. Sci.' ( section ⨝ section.course_id = course.course_id course )
π ID (instructor) - π ID (teaches)
π year σ (course_id='CS-101') (section)
π capacity (classroom)
π course.title, teaches.semester, teaches.year σ instructor.ID = teaches.ID and instructor.name = 'Einstein' and course.course_id = teaches.course_id ((course) ⨯ (teaches) ⨯ (instructor))
